version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_eukles
      MYSQL_USER: test_eukles
      MYSQL_PASSWORD: test_eukles
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql/data:/var/lib/mysql
  php:
    container_name: php
    build:
      context: .docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/html/
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
